import { describe, expect, test } from "bun:test";
import { MockLanguageModelV4 } from "ai/test";
import { llm, Policy, type PolicyOptions } from "./index";

const noSecretsPolicy: PolicyOptions = {
  id: "no-secrets",
  name: "No secrets",
  description: "Prevents sensitive data exposure.",
  instruction: "Block exposed API keys and secrets.",
  message: "Do not share secrets.",
};

const stayInScopePolicy: PolicyOptions = {
  id: "stay-in-scope",
  name: "Stay in scope",
  description: "Keeps the assistant focused on the product.",
  instruction: "Block requests outside the assistant's intended scope.",
  message: "That request is outside this assistant's scope.",
};

describe("llm", () => {
  test("returns findings generated by an AI SDK language model", async () => {
    const evaluator = llm(
      new MockLanguageModelV4({
        doGenerate: createObjectGeneration({
          findings: [
            {
              policyId: "no-secrets",
              passed: false,
              reason: "The output contained an API key.",
              confidence: 0.97,
            },
          ],
        }),
      }),
    );

    const findings = await evaluator({
      request: {
        type: "output",
        content: "sk_live_123",
      },
      policies: [new Policy(noSecretsPolicy)],
    });

    expect(findings).toEqual([
      {
        policyId: "no-secrets",
        passed: false,
        reason: "The output contained an API key.",
        confidence: 0.97,
      },
    ]);
  });

  test("includes input, output, and tool requests in the model prompt", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createObjectGeneration({
        findings: [
          {
            policyId: "stay-in-scope",
            passed: true,
          },
        ],
      }),
    });
    const evaluator = llm(model);

    await evaluator({
      request: {
        type: "input",
        content: "Can you write a test?",
      },
      policies: [new Policy(stayInScopePolicy)],
    });
    await evaluator({
      request: {
        type: "output",
        content: "Here is a safe summary.",
      },
      policies: [new Policy(stayInScopePolicy)],
    });
    await evaluator({
      request: {
        type: "tool",
        name: "sendEmail",
        arguments: {
          to: "security@example.com",
        },
      },
      policies: [new Policy(stayInScopePolicy)],
    });

    const prompts = model.doGenerateCalls.map((call) => JSON.stringify(call.prompt));

    expect(prompts[0]).toContain('\\"type\\": \\"input\\"');
    expect(prompts[0]).toContain('\\"content\\": \\"Can you write a test?\\"');
    expect(prompts[1]).toContain('\\"type\\": \\"output\\"');
    expect(prompts[1]).toContain('\\"content\\": \\"Here is a safe summary.\\"');
    expect(prompts[2]).toContain('\\"type\\": \\"tool\\"');
    expect(prompts[2]).toContain('\\"name\\": \\"sendEmail\\"');
    expect(prompts[2]).toContain('\\"to\\": \\"security@example.com\\"');
  });

  test("uses custom system instructions when provided", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createObjectGeneration({
        findings: [
          {
            policyId: "no-secrets",
            passed: true,
          },
        ],
      }),
    });
    const evaluator = llm(model, {
      system: "Use strict internal review guidance.",
      temperature: 0,
    });

    await evaluator({
      request: {
        type: "input",
        content: "Hello",
      },
      policies: [new Policy(noSecretsPolicy)],
    });

    const call = model.doGenerateCalls[0];
    expect(call).toBeDefined();

    if (call === undefined) {
      throw new Error("Expected the mock model to receive one generate call.");
    }

    expect(JSON.stringify(call.prompt)).toContain("Use strict internal review guidance.");
    expect(call.temperature).toBe(0);
  });

  test("rejects model findings for unknown policies", async () => {
    const evaluator = llm(
      new MockLanguageModelV4({
        doGenerate: createObjectGeneration({
          findings: [
            {
              policyId: "unknown-policy",
              passed: false,
            },
          ],
        }),
      }),
    );

    await expect(
      evaluator({
        request: {
          type: "input",
          content: "Hello",
        },
        policies: [new Policy(noSecretsPolicy)],
      }),
    ).rejects.toThrow("unknown policy id");
  });

  test("rejects model responses that omit configured policies", async () => {
    const evaluator = llm(
      new MockLanguageModelV4({
        doGenerate: createObjectGeneration({
          findings: [
            {
              policyId: "no-secrets",
              passed: true,
            },
          ],
        }),
      }),
    );

    await expect(
      evaluator({
        request: {
          type: "input",
          content: "Hello",
        },
        policies: [new Policy(noSecretsPolicy), new Policy(stayInScopePolicy)],
      }),
    ).rejects.toThrow("omitted findings");
  });
});

function createObjectGeneration(object: unknown) {
  return async () => ({
    content: [
      {
        type: "text" as const,
        text: JSON.stringify(object),
      },
    ],
    finishReason: {
      unified: "stop" as const,
      raw: undefined,
    },
    usage: {
      inputTokens: {
        total: 10,
        noCache: 10,
        cacheRead: undefined,
        cacheWrite: undefined,
      },
      outputTokens: {
        total: 20,
        text: 20,
        reasoning: undefined,
      },
    },
    warnings: [],
  });
}
