import { describe, expect, test } from "bun:test";
import { MockLanguageModelV4 } from "ai/test";
import {
  type DeniedPolicyDecision,
  generateViolationResponse,
  Policy,
  type PolicyDecision,
  type PolicyOptions,
} from "./index";

const noSecretsPolicy: PolicyOptions = {
  id: "no-secrets",
  name: "No secrets",
  description: "Prevents sensitive data exposure.",
  instruction: "Block exposed API keys and secrets.",
  message: "Do not share secrets.",
};

const stayInScopePolicy: PolicyOptions = {
  id: "stay-in-scope",
  name: "Stay in scope",
  description: "Keeps the assistant focused on the product.",
  instruction: "Block requests outside the assistant's intended scope.",
  message: "That request is outside this assistant's scope.",
};

describe("generateViolationResponse", () => {
  test("returns response text generated by an AI SDK language model", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createTextGeneration("I cannot help share secrets, but I can help rotate them."),
    });

    const response = await generateViolationResponse(model, createDeniedDecision());

    expect(response).toBe("I cannot help share secrets, but I can help rotate them.");
  });

  test("includes request and violation context in the model prompt", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createTextGeneration("I cannot help with that request."),
    });

    await generateViolationResponse(model, createDeniedDecision());

    const prompt = JSON.stringify(model.doGenerateCalls[0]?.prompt);

    expect(prompt).toContain('\\"type\\": \\"output\\"');
    expect(prompt).toContain('\\"content\\": \\"sk_live_123\\"');
    expect(prompt).toContain('\\"message\\": \\"Do not share secrets.\\"');
    expect(prompt).toContain('\\"id\\": \\"no-secrets\\"');
    expect(prompt).toContain('\\"name\\": \\"No secrets\\"');
    expect(prompt).toContain('\\"reason\\": \\"The output contained an API key.\\"');
    expect(prompt).toContain('\\"confidence\\": 0.97');
  });

  test("uses custom instructions and forwards generation options", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createTextGeneration("Please rephrase the request without the secret."),
    });

    await generateViolationResponse(model, createDeniedDecision(), {
      system: "Write in Acme's support voice.",
      instructions: "Mention that the user can redact the credential.",
      temperature: 0,
      maxOutputTokens: 120,
    });

    const call = model.doGenerateCalls[0];
    expect(call).toBeDefined();

    if (call === undefined) {
      throw new Error("Expected the mock model to receive one generate call.");
    }

    expect(JSON.stringify(call.prompt)).toContain("Write in Acme's support voice.");
    expect(JSON.stringify(call.prompt)).toContain(
      "Mention that the user can redact the credential.",
    );
    expect(call.temperature).toBe(0);
    expect(call.maxOutputTokens).toBe(120);
  });

  test("includes localized request and violation text unchanged in the prompt", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createTextGeneration("Jeg kan ikke dele hemmeligheter."),
    });

    await generateViolationResponse(
      model,
      createDeniedDecision({
        request: {
          type: "output",
          content: "Her er nøkkelen: sk_live_123. تماس بعداً.",
        },
        violations: [
          {
            policy: new Policy({
              ...noSecretsPolicy,
              name: "Ingen hemmeligheter",
              description: "Hindrer deling av sensitive nøkler.",
              message: "Ikke del hemmeligheter.",
            }),
            finding: {
              policyId: "no-secrets",
              passed: false,
              reason: "Svaret inneholdt en API-nøkkel.",
              confidence: 0.97,
            },
            message: "Ikke del hemmeligheter.",
          },
        ],
      }),
    );

    const prompt = JSON.stringify(model.doGenerateCalls[0]?.prompt);

    expect(prompt).toContain("Her er nøkkelen: sk_live_123. تماس بعداً.");
    expect(prompt).toContain("Ingen hemmeligheter");
    expect(prompt).toContain("Hindrer deling av sensitive nøkler.");
    expect(prompt).toContain("Svaret inneholdt en API-nøkkel.");
    expect(prompt).toContain("Ikke del hemmeligheter.");
  });

  test("includes explicit response locale and forwards generation options", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createTextGeneration("Jeg kan ikke hjelpe med å dele hemmeligheter."),
    });

    await generateViolationResponse(model, createDeniedDecision(), {
      locale: "nb-NO",
      temperature: 0,
      maxOutputTokens: 80,
    });

    const call = model.doGenerateCalls[0];
    expect(call).toBeDefined();

    if (call === undefined) {
      throw new Error("Expected the mock model to receive one generate call.");
    }

    const prompt = JSON.stringify(call.prompt);

    expect(prompt).toContain('\\"responseLocale\\": \\"nb-NO\\"');
    expect(prompt).toContain("Use the provided responseLocale");
    expect(call.temperature).toBe(0);
    expect(call.maxOutputTokens).toBe(80);
  });

  test("uses locale inference guidance when response locale is omitted", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createTextGeneration("I cannot help with that request."),
    });

    await generateViolationResponse(model, createDeniedDecision());

    const prompt = JSON.stringify(model.doGenerateCalls[0]?.prompt);

    expect(prompt).toContain(
      "Infer the appropriate response language/locale from the request and denial context.",
    );
    expect(prompt).not.toContain("responseLocale");
  });

  test("includes multiple violations in the prompt", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createTextGeneration("I cannot help with that request."),
    });

    await generateViolationResponse(
      model,
      createDeniedDecision({
        violations: [
          {
            policy: new Policy(noSecretsPolicy),
            finding: {
              policyId: "no-secrets",
              passed: false,
            },
            message: "Do not share secrets.",
          },
          {
            policy: new Policy(stayInScopePolicy),
            finding: {
              policyId: "stay-in-scope",
              passed: false,
            },
            message: "That request is outside this assistant's scope.",
          },
        ],
      }),
    );

    const prompt = JSON.stringify(model.doGenerateCalls[0]?.prompt);

    expect(prompt).toContain('\\"id\\": \\"no-secrets\\"');
    expect(prompt).toContain('\\"id\\": \\"stay-in-scope\\"');
    expect(prompt).toContain("That request is outside this assistant's scope.");
  });

  test("accepts denied decisions after policy decision narrowing", async () => {
    const model = new MockLanguageModelV4({
      doGenerate: createTextGeneration("I cannot help with that request."),
    });
    const decision: PolicyDecision = createDeniedDecision();

    if (!decision.allowed) {
      const deniedDecision: DeniedPolicyDecision = decision;
      const response = await generateViolationResponse(model, deniedDecision);

      expect(response).toBe("I cannot help with that request.");
    }
  });
});

function createDeniedDecision(overrides: Partial<DeniedPolicyDecision> = {}): DeniedPolicyDecision {
  return {
    allowed: false,
    request: {
      type: "output",
      content: "sk_live_123",
    },
    findings: [
      {
        policyId: "no-secrets",
        passed: false,
        reason: "The output contained an API key.",
        confidence: 0.97,
      },
    ],
    violations: [
      {
        policy: new Policy(noSecretsPolicy),
        finding: {
          policyId: "no-secrets",
          passed: false,
          reason: "The output contained an API key.",
          confidence: 0.97,
        },
        message: "Do not share secrets.",
      },
    ],
    escalations: [],
    ...overrides,
  };
}

function createTextGeneration(text: string) {
  return async () => ({
    content: [
      {
        type: "text" as const,
        text,
      },
    ],
    finishReason: {
      unified: "stop" as const,
      raw: undefined,
    },
    usage: {
      inputTokens: {
        total: 10,
        noCache: 10,
        cacheRead: undefined,
        cacheWrite: undefined,
      },
      outputTokens: {
        total: 20,
        text: 20,
        reasoning: undefined,
      },
    },
    warnings: [],
  });
}
