import { describe, expect, test } from "bun:test";
import {
  type DeniedPolicyDecision,
  generateViolationResponse,
  Policy,
  PolicyEvaluationError,
  type PolicyDecision,
  type PolicyOptions,
  type ScopraModel,
  type ScopraTextInput,
  ViolationResponseError,
} from "./index";

const noSecretsPolicy: PolicyOptions = {
  id: "no-secrets",
  name: "No secrets",
  description: "Prevents sensitive data exposure.",
  instruction: "Block exposed API keys and secrets.",
  denial: "Do not share secrets.",
};

const stayInScopePolicy: PolicyOptions = {
  id: "stay-in-scope",
  name: "Stay in scope",
  description: "Keeps the assistant focused on the product.",
  instruction: "Block requests outside the assistant's intended scope.",
  denial: "That request is outside this assistant's scope.",
};

describe("generateViolationResponse", () => {
  test("returns response text generated by a Scopra model", async () => {
    const model = createTextModel("I cannot help share secrets, but I can help rotate them.");

    const response = await generateViolationResponse(model, createDeniedDecision());

    expect(response).toBe("I cannot help share secrets, but I can help rotate them.");
  });

  test("includes request and violation context in the model prompt", async () => {
    const model = createTextModel("I cannot help with that request.");

    await generateViolationResponse(model, createDeniedDecision());

    const prompt = model.generateTextCalls[0]?.prompt;

    expect(prompt).toContain('"content": "sk_live_123"');
    expect(prompt).toContain('"denial": "Do not share secrets."');
    expect(prompt).toContain('"id": "no-secrets"');
    expect(prompt).toContain('"name": "No secrets"');
    expect(prompt).toContain('"reason": "The output contained an API key."');
    expect(prompt).toContain('"confidence": 0.97');
    expect(prompt).toContain('"severity": "critical"');
  });

  test("uses custom instructions and forwards model options", async () => {
    const model = createTextModel("Please rephrase the request without the secret.");

    await generateViolationResponse(model, createDeniedDecision(), {
      system: "Write in Acme's support voice.",
      instructions: "Mention that the user can redact the credential.",
      modelOptions: {
        temperature: 0,
        maxOutputTokens: 120,
      },
    });

    const call = model.generateTextCalls[0];
    expect(call).toBeDefined();

    if (call === undefined) {
      throw new Error("Expected the model to receive one generateText call.");
    }

    expect(call.system).toBe("Write in Acme's support voice.");
    expect(call.prompt).toContain("Mention that the user can redact the credential.");
    expect(call.modelOptions).toEqual({
      temperature: 0,
      maxOutputTokens: 120,
    });
  });

  test("includes localized request and violation text unchanged in the prompt", async () => {
    const model = createTextModel("Jeg kan ikke dele hemmeligheter.");

    await generateViolationResponse(
      model,
      createDeniedDecision({
        request: {
          content: "Her er nøkkelen: sk_live_123. تماس بعداً.",
        },
        violations: [
          {
            policy: new Policy({
              ...noSecretsPolicy,
              name: "Ingen hemmeligheter",
              description: "Hindrer deling av sensitive nøkler.",
              denial: "Ikke del hemmeligheter.",
            }),
            finding: {
              policyId: "no-secrets",
              passed: false,
              reason: "Svaret inneholdt en API-nøkkel.",
              confidence: 0.97,
            },
            denial: "Ikke del hemmeligheter.",
          },
        ],
      }),
    );

    const prompt = model.generateTextCalls[0]?.prompt;

    expect(prompt).toContain("Her er nøkkelen: sk_live_123. تماس بعداً.");
    expect(prompt).toContain("Ingen hemmeligheter");
    expect(prompt).toContain("Hindrer deling av sensitive nøkler.");
    expect(prompt).toContain("Svaret inneholdt en API-nøkkel.");
    expect(prompt).toContain("Ikke del hemmeligheter.");
  });

  test("includes explicit response locale and forwards model options", async () => {
    const model = createTextModel("Jeg kan ikke hjelpe med å dele hemmeligheter.");

    await generateViolationResponse(model, createDeniedDecision(), {
      locale: "nb-NO",
      modelOptions: {
        temperature: 0,
        maxOutputTokens: 80,
      },
    });

    const call = model.generateTextCalls[0];
    expect(call).toBeDefined();

    if (call === undefined) {
      throw new Error("Expected the model to receive one generateText call.");
    }

    const prompt = call.prompt;

    expect(prompt).toContain('"responseLocale": "nb-NO"');
    expect(prompt).toContain("Use the provided responseLocale");
    expect(call.modelOptions).toEqual({
      temperature: 0,
      maxOutputTokens: 80,
    });
  });

  test("uses locale inference guidance when response locale is omitted", async () => {
    const model = createTextModel("I cannot help with that request.");

    await generateViolationResponse(model, createDeniedDecision());

    const prompt = model.generateTextCalls[0]?.prompt;

    expect(prompt).toContain(
      "Infer the appropriate response language/locale from the request and denial context.",
    );
    expect(prompt).not.toContain("responseLocale");
  });

  test("includes multiple violations in the prompt", async () => {
    const model = createTextModel("I cannot help with that request.");

    await generateViolationResponse(
      model,
      createDeniedDecision({
        violations: [
          {
            policy: new Policy(noSecretsPolicy),
            finding: {
              policyId: "no-secrets",
              passed: false,
            },
            denial: "Do not share secrets.",
          },
          {
            policy: new Policy(stayInScopePolicy),
            finding: {
              policyId: "stay-in-scope",
              passed: false,
            },
            denial: "That request is outside this assistant's scope.",
          },
        ],
      }),
    );

    const prompt = model.generateTextCalls[0]?.prompt;

    expect(prompt).toContain('"id": "no-secrets"');
    expect(prompt).toContain('"id": "stay-in-scope"');
    expect(prompt).toContain("That request is outside this assistant's scope.");
  });

  test("accepts denied decisions after policy decision narrowing", async () => {
    const model = createTextModel("I cannot help with that request.");
    const decision: PolicyDecision = createDeniedDecision();

    if (!decision.allowed) {
      const deniedDecision: DeniedPolicyDecision = decision;
      const response = await generateViolationResponse(model, deniedDecision);

      expect(response).toBe("I cannot help with that request.");
    }
  });

  test("wraps response model failures in a violation response error", async () => {
    const cause = new Error("response model failed after seeing sk_live_123");
    const model = createFailingTextModel(cause);

    const error = await captureError(() =>
      generateViolationResponse(model, createDeniedDecision()),
    );

    expect(error).toBeInstanceOf(ViolationResponseError);
    expect(error).toMatchObject({
      code: "violation_response_failed",
      publicMessage: "A policy denial response could not be generated.",
      context: {
        policyIds: ["no-secrets"],
        phase: "violation_response",
      },
      cause,
    });
    expect(JSON.stringify((error as ViolationResponseError).context)).not.toContain("sk_live_123");
  });

  test("rethrows typed Scopra errors from response models unchanged", async () => {
    const cause = new PolicyEvaluationError("Nested policy evaluation failed.", {
      code: "policy_evaluator_failed",
      context: {
        policyIds: ["agent-scope"],
        phase: "policy_evaluator",
      },
    });
    const model = createFailingTextModel(cause);

    const error = await captureError(() =>
      generateViolationResponse(model, createDeniedDecision()),
    );

    expect(error).toBe(cause);
  });
});

function createDeniedDecision(overrides: Partial<DeniedPolicyDecision> = {}): DeniedPolicyDecision {
  return {
    allowed: false,
    request: {
      content: "sk_live_123",
    },
    findings: [
      {
        policyId: "no-secrets",
        passed: false,
        reason: "The output contained an API key.",
        confidence: 0.97,
        severity: "critical",
      },
    ],
    violations: [
      {
        policy: new Policy(noSecretsPolicy),
        finding: {
          policyId: "no-secrets",
          passed: false,
          reason: "The output contained an API key.",
          confidence: 0.97,
          severity: "critical",
        },
        denial: "Do not share secrets.",
      },
    ],
    escalations: [],
    ...overrides,
  };
}

type TestTextModel = ScopraModel & {
  readonly generateTextCalls: ScopraTextInput[];
};

function createTextModel(text: string): TestTextModel {
  const generateTextCalls: ScopraTextInput[] = [];

  return {
    generateTextCalls,
    async generateText(input) {
      generateTextCalls.push(input);
      return text;
    },
    async generateObject() {
      throw new Error("Unexpected generateObject call.");
    },
  };
}

function createFailingTextModel(error: Error): TestTextModel {
  const generateTextCalls: ScopraTextInput[] = [];

  return {
    generateTextCalls,
    async generateText(input) {
      generateTextCalls.push(input);
      throw error;
    },
    async generateObject() {
      throw new Error("Unexpected generateObject call.");
    },
  };
}

async function captureError(operation: () => Promise<unknown>): Promise<unknown> {
  try {
    await operation();
  } catch (error) {
    return error;
  }

  throw new Error("Expected operation to throw.");
}
